apiVersion: v1
kind: Deployment
metadata:
  name: turtle-deployment
  namesapce: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      lables:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:stable
